### ISSUE TITLE
Tax issue

### ISSUE THREAD

**Issue by RickDBCN** [sensson/whmcs-moneybird#13]
We have our prices set up including TAX. However Moneybird adds tax on top of the invoice where tax is already added.
Where do we change this?

**Comment by ju5t** [comment]
This isn't supported at the moment. It assumes WHMCS stores prices excl. VAT. They should. They probably don't because WHMCS hasn't cared much about accounting in the past.

In this file we set the value of each invoice line:

https://github.com/sensson/whmcs-moneybird/blob/9c6b22194b289c58e9641c3416dcb4f2dc93861d/lib/Models/Invoice.php#L192

If you're only doing business in your own country this is an easy change. If you don't, it's a lot harder if WHMCS doesn't store prices excl. VAT, because you have to reverse the VAT rate yourself. 

We're not in the position to make this ourselves at the moment.
