### ISSUE TITLE
Only 3 invoices are synced

### ISSUE THREAD

**Issue by JEEBEE123** [sensson/whmcs-moneybird#17]
I'm currently facing this issue and I just can't find a solution.

The cron only syncs 3 invoices, but there are ~90 invoices in WHMCS. 

Any idea?

![Screenshot_3](https://user-images.githubusercontent.com/38722343/99803201-52f74880-2b39-11eb-863a-c8f4f8804d3b.png)

**Comment by JEEBEE123** [comment]
Hmm, I've found this in my database. 

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '800' for key 'mod_moneybird_customer_links_whmcs_customer_id_unique' (SQL: insert into `mod_moneybird_customer_links` (`whmcs_customer_id`, `moneybird_customer_id`) values (800, 16))`

**Comment by ju5t** [comment]
I'm sorry for not getting back to you sooner.

The issue is most likely originating from this part of the module.

https://github.com/sensson/whmcs-moneybird/blob/9c6b22194b289c58e9641c3416dcb4f2dc93861d/lib/Models/Client.php#L123-L130

That doesn't make sense though. Because earlier on we fetch the link from the database:

https://github.com/sensson/whmcs-moneybird/blob/9c6b22194b289c58e9641c3416dcb4f2dc93861d/lib/Models/Client.php#L77

We would only create the a new link if the previous one didn't exist.

Can you check if `whmcs_customer_id` 800 exists in `mod_moneybird_customer_links`?
