### ISSUE TITLE
Everything importing into moneybird is in euros and unpaid.

### ISSUE THREAD

**Issue by RXWatcher** [sensson/whmcs-moneybird#31]
1) Thank you for the software. It was very easy to run composer and add the module. 2 minutes. 

2) Past invoices are being imported into moneybird as unpaid even when marked paid in whmcs. Any idea how to get them marked as paid?

3) Everything imports into moneybird as euros. The default currency in whmcs is USD. I left it as USD and now have a mix of euros and usd. I can't change the default from usd in whmcs as it's too late once you have customers and invoices. Moneybird seems to support both so is it possible change the module to recognize both while importing into moneybird? 

Thank you, again,  for providing this module.

**Comment by ju5t** [comment]
@RXWatcher sorry for not responding earlier, I completely missed this issue.

2. Past invoices shouldn't have been imported unless you didn't set the the first invoice number that you want to synchronise. I'd suggest speaking to something who can actually give you financial advise on this so things go right. It might be best to try and remove the invoices (or credit them) but I definitely suggest speaking to a professional first.
3. Hm. This probably happens because it's the default in Moneybird. Having said that, it's probably something that should (and can) be enforced from this module.

So, about 3. I'm not sure if you can PR this because I'm somewhat short on time at this moment. But you need to set `currency` on the sales invoice, the code for it is around [Invoice.php#L198](https://github.com/sensson/whmcs-moneybird/blob/main/lib/Models/Invoice.php#L198). 

If you add the following on line 203 or so:

```php
$salesInvoice->currency = $this->getCurrencyCodeAttribute();
```

I think it should work. But this is untested and I don't know in which format WHMCS returns the currency code to you.
